### ISSUE TITLE
error

### ISSUE THREAD

**Issue by neverbxrn** [face-hh/discordmium#8]
[Running] node "c:\Users\User\Downloads\discordmium-main\start.js"
Connected to Discord!
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordRESTError [50001]: Missing Access
    at RequestHandler.request (c:\Users\User\node_modules\eris\lib\rest\RequestHandler.js:75:15)
    at Client.bulkEditGuildCommands (c:\Users\User\node_modules\eris\lib\Client.js:407:36)
    at Client.<anonymous> (c:\Users\User\node_modules\discordmium\index.js:56:7)
    at Client.emit (node:events:513:28)
    at Shard.<anonymous> (c:\Users\User\node_modules\eris\lib\gateway\ShardManager.js:55:30)
    at Shard.emit (node:events:513:28)
    at Shard.checkReady (c:\Users\User\node_modules\eris\lib\gateway\Shard.js:95:23)
    at Shard.restartGuildCreateTimeout (c:\Users\User\node_modules\eris\lib\gateway\Shard.js:546:29)
    at Shard.wsEvent (c:\Users\User\node_modules\eris\lib\gateway\Shard.js:1219:30)
    at Shard.onPacket (c:\Users\User\node_modules\eris\lib\gateway\Shard.js:405:26)
    
[Done] exited with code=1 in 1.057 seconds

sooo, what is going on here?

**Comment by face-hh** [comment]
Invite your bot with the scope `application.commands`.

**Comment by neverbxrn** [comment]
thx forgot

**Comment by KnoyanMitsu** [comment]
same error i already scope 'application.commads' but still same error
